[window]
dynamic_padding = true
opacity = 0.99
blur = true

[font]
normal = { family = "IosevkaTermSlab Nerd Font", style = "Regular" }
bold = { family = "IosevkaTermSlab Nerd Font", style = "Bold" }
italic = { family = "IosevkaTermSlab Nerd Font", style = "Italic" }
bold_italic = { family = "IosevkaTermSlab Nerd Font", style = "Bold Italic" }
size = 16.0

[font.offset]
x = 0
y = 0

[terminal.shell]
program = "/usr/bin/fish"
args = ["--login"]

# Oscura Theme for Alacritty (TOML)
[scrolling]
history = 10000
multiplier = 3

[colors]
# Default colors
primary = { background = "#0B0B0F", foreground = "#E6E6E6" }

# Normal colors
normal = { black = "#232323", red = "#D84F68", green = "#54C0A3", yellow = "#E6E7A3", blue = "#479FFA", magenta = "#9592A4", cyan = "#4EBE96", white = "#E6E6E6" }

# Bright colors
bright = { black = "#46474F", red = "#FF5C5C", green = "#76DEC0", yellow = "#F9F9C2", blue = "#6BB2FF", magenta = "#B4B0C4", cyan = "#6BD6B1", white = "#FFFFFF" }

# Selection colors
selection = { text = "#0B0B0F", background = "#E6E7A3" }

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 750
unfocused_hollow = true
thickness = 0.15
