[window]
opacity = 0.95
blur = true

[font]
normal = { family = "IosevkaTermSlab Nerd Font", style = "Regular" }
bold = { family = "IosevkaTermSlab Nerd Font", style = "Bold" }
italic = { family = "IosevkaTermSlab Nerd Font", style = "Italic" }
bold_italic = { family = "IosevkaTermSlab Nerd Font", style = "Bold Italic" }
size = 16.0

[font.offset]
x = 0
y = 0

[terminal.shell]
program = "/usr/bin/fish"
args = ["--login"]

[colors.primary]
background = "#171717"
foreground = "#f2f0e3"

[colors.cursor]
text = "#171717"
cursor = "#57ffbd"

[colors.selection]
text = "#f2f0e3"
background = "#3d3d3d"

[colors.normal]
black = "#171717"
red = "#fe7457"
green = "#57ffbd"
yellow = "#ffd357"
blue = "#57bdff"
magenta = "#ff57bd"
cyan = "#57e9ff"
white = "#f2f0e3"

[colors.bright]
black = "#202020"
red = "#ff9480"
green = "#80ffcd"
yellow = "#ffe680"
blue = "#80cfff"
magenta = "#ff80cd"
cyan = "#80efff"
white = "#ffffff"
